import { Nodes } from '../model'

export const nodes: Nodes =[
  {
    id: 'power_sim_output',
    label: 'power_sim_output @ 12:1',
    comboId: 'accepted_matches',
    violations: 20014,
    partitions: 85,
  },
  {
    id: 'matches_without_nuna_pcp_available',
    label: 'matches_without_nuna_pcp_available @ 14:0',
    violations: 6379,
    partitions: 31,
  },
  {
    id: 'matches_without_nuna_pcp_available_plus_exclusion_info',
    label: 'matches_without_nuna_pcp_available_plus_exclusion_info @ 14:1',
    violations: 20110,
    partitions: 131,
  },
  {
    id: 'matches_excluded_from_experiment',
    label: 'matches_excluded_from_experiment @ 15:0',
    violations: 20343,
    partitions: 100,
  },
  {
    id: 'matches_excluded_from_experiment_subset_not_rejected',
    label: 'matches_excluded_from_experiment_subset_not_rejected @ 15:1',
    violations: 15735,
    partitions: 79,
  },
  { id: 'accepted_matches_excluded', label: 'accepted_matches_excluded @ 15:2', violations: 20959, partitions: 98 },
  { id: 'flag_accepted_assignments', label: 'flag_accepted_assignments @ 19:0', violations: 4139, partitions: 128 },
  {
    id: 'accepted_acknowledged_non_excluded_matches_w_treatment',
    label: 'accepted_acknowledged_non_excluded_matches_w_treatment @ 19:1',
    violations: 22284,
    partitions: 34,
  },
  { id: 'other_pcps', label: 'other_pcps @ 23:0', violations: 9891, partitions: 83 },
  {
    id: 'count_matches_by_csid_and_affiliation',
    label: 'count_matches_by_csid_and_affiliation @ 24:0',
    violations: 16389,
    partitions: 58,
  },
  {
    id: 'count_matches_by_csid_and_capacity_affiliation',
    label: 'count_matches_by_csid_and_capacity_affiliation @ 26:0',
    violations: 8428,
    partitions: 16,
  },
  {
    id: 'match_values_for_all_member_profiles_excl_unknown_gender',
    label: 'match_values_for_all_member_profiles_excl_unknown_gender @ 28:0',
    violations: 1612,
    partitions: 116,
  },
  {
    id: 'transactions_with_all_valid_pcp_options',
    label: 'transactions_with_all_valid_pcp_options @ 32:0',
    violations: 22720,
    partitions: 117,
  },
  {
    id: 'nearest_member_provider_address2',
    label: 'nearest_member_provider_address2 @ 34:0',
    violations: 8122,
    partitions: 30,
  },
  { id: 'closest_travel_time', label: 'closest_travel_time @ 34:1', violations: 22955, partitions: 69 },
  { id: 'pcps_nearby_to_mem_zipcode', label: 'pcps_nearby_to_mem_zipcode @ 34:2', violations: 16075, partitions: 87 },
  {
    id: 'transactions_with_all_valid_and_closest_pcp_options',
    label: 'transactions_with_all_valid_and_closest_pcp_options @ 35:0',
    violations: 15741,
    partitions: 16,
  },
  {
    id: 'lowest_match_value_per_transaction',
    label: 'lowest_match_value_per_transaction @ 38:0',
    violations: 18784,
    partitions: 114,
  },
  { id: 'unconstrained_PCPs_tmp', label: 'unconstrained_PCPs_tmp @ 38:1', violations: 20047, partitions: 107 },
  { id: 'unconstrained_PCPs', label: 'unconstrained_PCPs @ 38:2', violations: 18684, partitions: 53 },
  {
    id: 'accepted_matches_w_unconstrained_pcp',
    label: 'accepted_matches_w_unconstrained_pcp @ 40:0',
    violations: 19580,
    partitions: 111,
  },
  {
    id: 'accepted_matches_w_nuna_match_cost_and_quality',
    label: 'accepted_matches_w_nuna_match_cost_and_quality @ 42:0',
    violations: 5063,
    partitions: 16,
  },
  {
    id: 'accepted_matches_w_nuna_match_and_unconstrained_cost_and_quality',
    label: 'accepted_matches_w_nuna_match_and_unconstrained_cost_and_quality @ 42:1',
    violations: 23545,
    partitions: 19,
  },
  { id: 'matches_with_cs_default_pcp', label: 'matches_with_cs_default_pcp @ 45:0', violations: 11219, partitions: 92 },
  {
    id: 'matches_with_cs_default_pcp_without_match_values',
    label: 'matches_with_cs_default_pcp_without_match_values @ 46:0',
    violations: 21027,
    partitions: 58,
  },
  {
    id: 'num_matches_with_nuna_pcp_equal_caresource_pcp',
    label: 'num_matches_with_nuna_pcp_equal_caresource_pcp @ 47:0',
    violations: 24130,
    partitions: 31,
  },
  {
    id: 'compare_nuna_pcp_with_cs_pcp_in_treated_group',
    label: 'compare_nuna_pcp_with_cs_pcp_in_treated_group @ 48:0',
    violations: 20784,
    partitions: 103,
  },
  {
    id: 'accepted_matches_w_nuna_match_and_cs_match_cost_and_quality',
    label: 'accepted_matches_w_nuna_match_and_cs_match_cost_and_quality @ 49:0',
    comboId: 'accepted_matches',
    violations: 14684,
    partitions: 26,
  },
  {
    id: 'percent_of_transactions_without_enough_data_to_directly_compare',
    label: 'percent_of_transactions_without_enough_data_to_directly_compare @ 50:0',
    violations: 19184,
    partitions: 36,
  },
  {
    id: 'accepted_matches_w_nuna_match_and_cs_match_cost_and_quality_w_log_mv',
    label: 'accepted_matches_w_nuna_match_and_cs_match_cost_and_quality_w_log_mv @ 54:0',
    comboId: 'accepted_matches',
    violations: 15897,
    partitions: 87,
  },
  {
    id: 'savings_rate_with_power_sim_output',
    label: 'savings_rate_with_power_sim_output @ 54:1',
    comboId: 'accepted_matches',
    violations: 12669,
    partitions: 89,
  },
  {
    id: 'total_annualized_savings',
    label: 'total_annualized_savings @ 59:0',
    comboId: 'accepted_matches',
    violations: 19258,
    partitions: 126,
  },
  {
    id: 'comp_cost_to_cs_matches_by_dem',
    label: 'comp_cost_to_cs_matches_by_dem @ 62:0',
    comboId: 'accepted_matches',
    violations: 24388,
    partitions: 42,
  },
  {
    id: 'comp_cost_to_cs_matches_by_boe',
    label: 'comp_cost_to_cs_matches_by_boe @ 64:0',
    comboId: 'accepted_matches',
    violations: 12108,
    partitions: 32,
  },
  {
    id: 'quality_improvement_performance',
    label: 'quality_improvement_performance @ 68:0',
    comboId: 'accepted_matches',
    violations: 7476,
    partitions: 23,
  },
  {
    id: 'comp_quality_to_cs_matches_by_dem',
    label: 'comp_quality_to_cs_matches_by_dem @ 71:0',
    comboId: 'accepted_matches',
    violations: 18489,
    partitions: 80,
  },
  {
    id: 'comp_quality_to_cs_matches_by_boe',
    label: 'comp_quality_to_cs_matches_by_boe @ 73:0',
    comboId: 'accepted_matches',
    violations: 19966,
    partitions: 23,
  },
  {
    id: 'accepted_matches_w_nuna_match_and_unconstrained_cost_and_quality_w_log_mv',
    label: 'accepted_matches_w_nuna_match_and_unconstrained_cost_and_quality_w_log_mv @ 78:0',
    violations: 5977,
    partitions: 21,
  },
  {
    id: 'unconstrained_savings_rate_with_power_sim_output',
    label: 'unconstrained_savings_rate_with_power_sim_output @ 78:1',
    comboId: 'accepted_matches',
    violations: 24395,
    partitions: 88,
  },
  {
    id: 'provider_info_primary_address_only',
    label: 'provider_info_primary_address_only @ 88:0',
    violations: 22616,
    partitions: 86,
  },
  { id: 'nuna_match_provider_info', label: 'nuna_match_provider_info @ 88:1', violations: 4299, partitions: 56 },
  {
    id: 'matches_with_cs_default_pcp_without_match_values_w_group',
    label: 'matches_with_cs_default_pcp_without_match_values_w_group @ 89:0',
    violations: 3794,
    partitions: 77,
  },
  {
    id: 'num_matches_with_nuna_group_equal_caresource_group',
    label: 'num_matches_with_nuna_group_equal_caresource_group @ 89:1',
    violations: 6457,
    partitions: 41,
  },
  { id: 'nuna_match_metrics', label: 'nuna_match_metrics @ 89:2', violations: 5662, partitions: 63 },
  {
    id: 'accepted_acknowledged_non_excluded_matches_w_control',
    label: 'accepted_acknowledged_non_excluded_matches_w_control @ 90:0',
    violations: 23556,
    partitions: 19,
  },
  { id: 'control_provider_info', label: 'control_provider_info @ 90:1', violations: 10772, partitions: 54 },
  { id: 'control_match_metrics', label: 'control_match_metrics @ 91:0', violations: 1422, partitions: 128 },
  { id: 'overlap_providers', label: 'overlap_providers @ 92:0', violations: 24903, partitions: 76 },
  { id: 'overlap_practices', label: 'overlap_practices @ 92:1', violations: 10064, partitions: 71 },
  {
    id: 'all_control_matches_w_overlap_flags',
    label: 'all_control_matches_w_overlap_flags @ 92:2',
    violations: 12969,
    partitions: 17,
  },
  { id: 'overlap_metric_1', label: 'overlap_metric_1 @ 92:3', violations: 5566, partitions: 75 },
  { id: 'overlap_metric_2', label: 'overlap_metric_2 @ 92:4', violations: 13938, partitions: 58 },
  { id: 'overlap_metric_3', label: 'overlap_metric_3 @ 92:5', violations: 19487, partitions: 62 },
  { id: 'overlap_metric_4', label: 'overlap_metric_4 @ 92:6', violations: 19984, partitions: 21 },
  {
    id: 'top_10_practices_cs_matches',
    label: 'top_10_practices_cs_matches @ 96:0',
    violations: 14235,
    partitions: 126,
  },
  { id: 'nuna_matches_by_group', label: 'nuna_matches_by_group @ 96:1', violations: 17454, partitions: 101 },
  { id: 'overlap_provider_w_practice', label: 'overlap_provider_w_practice @ 96:2', violations: 7060, partitions: 54 },
  {
    id: 'all_matches_w_overlap_npi_practice',
    label: 'all_matches_w_overlap_npi_practice @ 96:3',
    violations: 21528,
    partitions: 44,
  },
  { id: 'groups_w_overlap_npi', label: 'groups_w_overlap_npi @ 96:4', violations: 2766, partitions: 32 },
  { id: 'recent_provider_extract', label: 'recent_provider_extract', violations: 16478, partitions: 108 },
  { id: 'assignment_history', label: 'assignment_history', violations: 20637, partitions: 133 },
  {
    id: 'AVRA_risk_adjuster__provider_measure',
    label: 'AVRA_risk_adjuster__provider_measure',
    violations: 13109,
    partitions: 59,
  },
  { id: 'match_history', label: 'match_history', violations: 20592, partitions: 102 },
  { id: 'AVRA_attribution', label: 'AVRA_attribution', violations: 2973, partitions: 65 },
  { id: 'demographic_capacity_cost', label: 'demographic_capacity_cost', violations: 9293, partitions: 38 },
  { id: 'pcpm_boe_crosswalk', label: 'pcpm_boe_crosswalk', violations: 8362, partitions: 105 },
  {
    id: 'nearest_member_provider_address',
    label: 'nearest_member_provider_address',
    violations: 24295,
    partitions: 132,
  },
  { id: 'match_value_table', label: 'match_value_table', violations: 7781, partitions: 24 },
  { id: 'filtered_valid_matches', label: 'filtered_valid_matches', violations: 17129, partitions: 80 },
  { id: 'last_successful_run', label: 'last_successful_run', violations: 13704, partitions: 110 },
  { id: 'experiment_exclusions', label: 'experiment_exclusions', violations: 10790, partitions: 60 },
  { id: 'compliance_adj_match_values', label: 'compliance_adj_match_values', violations: 11043, partitions: 109 },
  { id: 'pdb_provider_address', label: 'pdb_provider_address', violations: 9770, partitions: 65 },
  { id: 'provider_address', label: 'provider_address', violations: 15306, partitions: 73 },
  {
    id: 'power_sim_output_full',
    label: 'power_sim_output_full',
    comboId: 'accepted_matches',
    violations: 11527,
    partitions: 117,
  },
  { id: 'match_results', label: 'match_results', violations: 13455, partitions: 76 },
  { id: 'match_history_providers', label: 'match_history_providers', violations: 16577, partitions: 72 },
  { id: 'match_requests', label: 'match_requests', violations: 19441, partitions: 75 },
  { id: 'experiment_assignments', label: 'experiment_assignments', violations: 23823, partitions: 71 },
  { id: 'sink @ 1:0', label: 'sink @ 1:0', violations: 6494, partitions: 92 },
  { id: 'sink @ 6:1', label: 'sink @ 6:1', violations: 21791, partitions: 110 },
  { id: 'sink @ 9:0', label: 'sink @ 9:0', violations: 17134, partitions: 60 },
  { id: 'sink @ 12:2', label: 'sink @ 12:2', comboId: 'accepted_matches', violations: 24136, partitions: 123 },
  { id: 'sink @ 14:2', label: 'sink @ 14:2', violations: 12747, partitions: 91 },
  { id: 'sink @ 15:3', label: 'sink @ 15:3', violations: 11348, partitions: 21 },
  { id: 'sink @ 16:0', label: 'sink @ 16:0', violations: 9361, partitions: 116 },
  { id: 'sink @ 17:0', label: 'sink @ 17:0', violations: 24567, partitions: 67 },
  { id: 'sink @ 19:2', label: 'sink @ 19:2', violations: 5644, partitions: 20 },
  { id: 'sink @ 20:0', label: 'sink @ 20:0', violations: 9391, partitions: 62 },
  { id: 'sink @ 21:0', label: 'sink @ 21:0', violations: 19769, partitions: 45 },
  { id: 'sink @ 23:1', label: 'sink @ 23:1', violations: 17769, partitions: 112 },
  { id: 'sink @ 24:1', label: 'sink @ 24:1', violations: 1570, partitions: 115 },
  { id: 'sink @ 25:0', label: 'sink @ 25:0', violations: 16924, partitions: 16 },
  { id: 'sink @ 26:1', label: 'sink @ 26:1', violations: 14859, partitions: 73 },
  { id: 'sink @ 27:0', label: 'sink @ 27:0', violations: 18049, partitions: 31 },
  { id: 'sink @ 30:0', label: 'sink @ 30:0', violations: 22577, partitions: 77 },
  { id: 'sink @ 33:0', label: 'sink @ 33:0', violations: 18789, partitions: 105 },
  { id: 'sink @ 36:0', label: 'sink @ 36:0', violations: 8367, partitions: 96 },
  { id: 'sink @ 37:0', label: 'sink @ 37:0', violations: 9626, partitions: 63 },
  { id: 'sink @ 39:0', label: 'sink @ 39:0', violations: 10014, partitions: 18 },
  { id: 'sink @ 40:1', label: 'sink @ 40:1', violations: 6309, partitions: 108 },
  { id: 'sink @ 43:0', label: 'sink @ 43:0', violations: 10756, partitions: 47 },
  { id: 'sink @ 45:1', label: 'sink @ 45:1', violations: 24882, partitions: 54 },
  { id: 'sink @ 46:1', label: 'sink @ 46:1', violations: 15905, partitions: 100 },
  { id: 'sink @ 47:1', label: 'sink @ 47:1', violations: 10684, partitions: 55 },
  { id: 'sink @ 48:1', label: 'sink @ 48:1', violations: 24772, partitions: 122 },
  { id: 'sink @ 50:1', label: 'sink @ 50:1', violations: 9505, partitions: 111 },
  { id: 'sink @ 51:0', label: 'sink @ 51:0', comboId: 'accepted_matches', violations: 15955, partitions: 126 },
  { id: 'sink @ 54:2', label: 'sink @ 54:2', violations: 22659, partitions: 15 },
  { id: 'sink @ 55:0', label: 'sink @ 55:0', comboId: 'accepted_matches', violations: 21034, partitions: 123 },
  { id: 'sink @ 56:0', label: 'sink @ 56:0', violations: 7396, partitions: 44 },
  { id: 'sink @ 57:0', label: 'sink @ 57:0', comboId: 'accepted_matches', violations: 19788, partitions: 71 },
  { id: 'sink @ 58:0', label: 'sink @ 58:0', comboId: 'accepted_matches', violations: 7741, partitions: 44 },
  { id: 'sink @ 59:1', label: 'sink @ 59:1', comboId: 'accepted_matches', violations: 19298, partitions: 84 },
  { id: 'sink @ 60:1', label: 'sink @ 60:1', comboId: 'accepted_matches', violations: 18180, partitions: 117 },
  { id: 'sink @ 62:1', label: 'sink @ 62:1', comboId: 'accepted_matches', violations: 19610, partitions: 78 },
  { id: 'sink @ 64:1', label: 'sink @ 64:1', comboId: 'accepted_matches', violations: 12533, partitions: 80 },
  { id: 'sink @ 68:1', label: 'sink @ 68:1', comboId: 'accepted_matches', violations: 20200, partitions: 37 },
  { id: 'sink @ 69:0', label: 'sink @ 69:0', comboId: 'accepted_matches', violations: 16892, partitions: 125 },
  { id: 'sink @ 71:1', label: 'sink @ 71:1', comboId: 'accepted_matches', violations: 16538, partitions: 61 },
  { id: 'sink @ 73:1', label: 'sink @ 73:1', comboId: 'accepted_matches', violations: 8904, partitions: 108 },
  { id: 'sink @ 77:0', label: 'sink @ 77:0', violations: 21363, partitions: 104 },
  { id: 'sink @ 78:2', label: 'sink @ 78:2', comboId: 'accepted_matches', violations: 13733, partitions: 71 },
  { id: 'sink @ 79:0', label: 'sink @ 79:0', violations: 18542, partitions: 30 },
  { id: 'sink @ 80:0', label: 'sink @ 80:0', comboId: 'accepted_matches', violations: 11352, partitions: 114 },
  { id: 'sink @ 81:0', label: 'sink @ 81:0', violations: 15174, partitions: 52 },
  { id: 'sink @ 82:0', label: 'sink @ 82:0', comboId: 'accepted_matches', violations: 2803, partitions: 56 },
  { id: 'sink @ 83:0', label: 'sink @ 83:0', violations: 22032, partitions: 18 },
  { id: 'sink @ 85:0', label: 'sink @ 85:0', comboId: 'accepted_matches', violations: 13924, partitions: 131 },
  { id: 'sink @ 87:0', label: 'sink @ 87:0', violations: 22432, partitions: 39 },
  { id: 'sink @ 88:2', label: 'sink @ 88:2', violations: 11999, partitions: 107 },
  { id: 'sink @ 90:2', label: 'sink @ 90:2', violations: 22957, partitions: 48 },
  { id: 'sink @ 91:1', label: 'sink @ 91:1', violations: 22441, partitions: 86 },
  { id: 'sink @ 94:0', label: 'sink @ 94:0', violations: 2197, partitions: 112 },
  { id: 'sink @ 95:0', label: 'sink @ 95:0', violations: 23646, partitions: 75 },
  { id: 'sink @ 96:5', label: 'sink @ 96:5', violations: 21745, partitions: 84 },
  { id: 'sink @ 97:0', label: 'sink @ 97:0', violations: 22008, partitions: 120 },
]
