import { Nodes } from '../model'

export const nodes: Nodes = [
  { id: 'power_sim_output', label: 'power_sim_output @ 12:1', comboId: 'accepted_matches' },
  { id: 'matches_without_nuna_pcp_available', label: 'matches_without_nuna_pcp_available @ 14:0' },
  {
    id: 'matches_without_nuna_pcp_available_plus_exclusion_info',
    label: 'matches_without_nuna_pcp_available_plus_exclusion_info @ 14:1',
  },
  { id: 'matches_excluded_from_experiment', label: 'matches_excluded_from_experiment @ 15:0' },
  {
    id: 'matches_excluded_from_experiment_subset_not_rejected',
    label: 'matches_excluded_from_experiment_subset_not_rejected @ 15:1',
  },
  { id: 'accepted_matches_excluded', label: 'accepted_matches_excluded @ 15:2' },
  { id: 'flag_accepted_assignments', label: 'flag_accepted_assignments @ 19:0' },
  {
    id: 'accepted_acknowledged_non_excluded_matches_w_treatment',
    label: 'accepted_acknowledged_non_excluded_matches_w_treatment @ 19:1',
  },
  { id: 'other_pcps', label: 'other_pcps @ 23:0' },
  { id: 'count_matches_by_csid_and_affiliation', label: 'count_matches_by_csid_and_affiliation @ 24:0' },
  {
    id: 'count_matches_by_csid_and_capacity_affiliation',
    label: 'count_matches_by_csid_and_capacity_affiliation @ 26:0',
  },
  {
    id: 'match_values_for_all_member_profiles_excl_unknown_gender',
    label: 'match_values_for_all_member_profiles_excl_unknown_gender @ 28:0',
  },
  { id: 'transactions_with_all_valid_pcp_options', label: 'transactions_with_all_valid_pcp_options @ 32:0' },
  { id: 'nearest_member_provider_address2', label: 'nearest_member_provider_address2 @ 34:0' },
  { id: 'closest_travel_time', label: 'closest_travel_time @ 34:1' },
  { id: 'pcps_nearby_to_mem_zipcode', label: 'pcps_nearby_to_mem_zipcode @ 34:2' },
  {
    id: 'transactions_with_all_valid_and_closest_pcp_options',
    label: 'transactions_with_all_valid_and_closest_pcp_options @ 35:0',
  },
  { id: 'lowest_match_value_per_transaction', label: 'lowest_match_value_per_transaction @ 38:0' },
  { id: 'unconstrained_PCPs_tmp', label: 'unconstrained_PCPs_tmp @ 38:1' },
  { id: 'unconstrained_PCPs', label: 'unconstrained_PCPs @ 38:2' },
  { id: 'accepted_matches_w_unconstrained_pcp', label: 'accepted_matches_w_unconstrained_pcp @ 40:0' },
  {
    id: 'accepted_matches_w_nuna_match_cost_and_quality',
    label: 'accepted_matches_w_nuna_match_cost_and_quality @ 42:0',
  },
  {
    id: 'accepted_matches_w_nuna_match_and_unconstrained_cost_and_quality',
    label: 'accepted_matches_w_nuna_match_and_unconstrained_cost_and_quality @ 42:1',
  },
  { id: 'matches_with_cs_default_pcp', label: 'matches_with_cs_default_pcp @ 45:0' },
  {
    id: 'matches_with_cs_default_pcp_without_match_values',
    label: 'matches_with_cs_default_pcp_without_match_values @ 46:0',
  },
  {
    id: 'num_matches_with_nuna_pcp_equal_caresource_pcp',
    label: 'num_matches_with_nuna_pcp_equal_caresource_pcp @ 47:0',
  },
  {
    id: 'compare_nuna_pcp_with_cs_pcp_in_treated_group',
    label: 'compare_nuna_pcp_with_cs_pcp_in_treated_group @ 48:0',
  },
  {
    id: 'accepted_matches_w_nuna_match_and_cs_match_cost_and_quality',
    label: 'accepted_matches_w_nuna_match_and_cs_match_cost_and_quality @ 49:0',
    comboId: 'accepted_matches',
  },
  {
    id: 'percent_of_transactions_without_enough_data_to_directly_compare',
    label: 'percent_of_transactions_without_enough_data_to_directly_compare @ 50:0',
  },
  {
    id: 'accepted_matches_w_nuna_match_and_cs_match_cost_and_quality_w_log_mv',
    label: 'accepted_matches_w_nuna_match_and_cs_match_cost_and_quality_w_log_mv @ 54:0',
    comboId: 'accepted_matches',
  },
  {
    id: 'savings_rate_with_power_sim_output',
    label: 'savings_rate_with_power_sim_output @ 54:1',
    comboId: 'accepted_matches',
  },
  {
    id: 'total_annualized_savings',
    label: 'total_annualized_savings @ 59:0',
    comboId: 'accepted_matches',
  },
  {
    id: 'comp_cost_to_cs_matches_by_dem',
    label: 'comp_cost_to_cs_matches_by_dem @ 62:0',
    comboId: 'accepted_matches',
  },
  {
    id: 'comp_cost_to_cs_matches_by_boe',
    label: 'comp_cost_to_cs_matches_by_boe @ 64:0',
    comboId: 'accepted_matches',
  },
  {
    id: 'quality_improvement_performance',
    label: 'quality_improvement_performance @ 68:0',
    comboId: 'accepted_matches',
  },
  {
    id: 'comp_quality_to_cs_matches_by_dem',
    label: 'comp_quality_to_cs_matches_by_dem @ 71:0',
    comboId: 'accepted_matches',
  },
  {
    id: 'comp_quality_to_cs_matches_by_boe',
    label: 'comp_quality_to_cs_matches_by_boe @ 73:0',
    comboId: 'accepted_matches',
  },
  {
    id: 'accepted_matches_w_nuna_match_and_unconstrained_cost_and_quality_w_log_mv',
    label: 'accepted_matches_w_nuna_match_and_unconstrained_cost_and_quality_w_log_mv @ 78:0',
  },
  {
    id: 'unconstrained_savings_rate_with_power_sim_output',
    label: 'unconstrained_savings_rate_with_power_sim_output @ 78:1',
    comboId: 'accepted_matches',
  },
  { id: 'provider_info_primary_address_only', label: 'provider_info_primary_address_only @ 88:0' },
  { id: 'nuna_match_provider_info', label: 'nuna_match_provider_info @ 88:1' },
  {
    id: 'matches_with_cs_default_pcp_without_match_values_w_group',
    label: 'matches_with_cs_default_pcp_without_match_values_w_group @ 89:0',
  },
  {
    id: 'num_matches_with_nuna_group_equal_caresource_group',
    label: 'num_matches_with_nuna_group_equal_caresource_group @ 89:1',
  },
  { id: 'nuna_match_metrics', label: 'nuna_match_metrics @ 89:2' },
  {
    id: 'accepted_acknowledged_non_excluded_matches_w_control',
    label: 'accepted_acknowledged_non_excluded_matches_w_control @ 90:0',
  },
  { id: 'control_provider_info', label: 'control_provider_info @ 90:1' },
  { id: 'control_match_metrics', label: 'control_match_metrics @ 91:0' },
  { id: 'overlap_providers', label: 'overlap_providers @ 92:0' },
  { id: 'overlap_practices', label: 'overlap_practices @ 92:1' },
  { id: 'all_control_matches_w_overlap_flags', label: 'all_control_matches_w_overlap_flags @ 92:2' },
  { id: 'overlap_metric_1', label: 'overlap_metric_1 @ 92:3' },
  { id: 'overlap_metric_2', label: 'overlap_metric_2 @ 92:4' },
  { id: 'overlap_metric_3', label: 'overlap_metric_3 @ 92:5' },
  { id: 'overlap_metric_4', label: 'overlap_metric_4 @ 92:6' },
  { id: 'top_10_practices_cs_matches', label: 'top_10_practices_cs_matches @ 96:0' },
  { id: 'nuna_matches_by_group', label: 'nuna_matches_by_group @ 96:1' },
  { id: 'overlap_provider_w_practice', label: 'overlap_provider_w_practice @ 96:2' },
  { id: 'all_matches_w_overlap_npi_practice', label: 'all_matches_w_overlap_npi_practice @ 96:3' },
  { id: 'groups_w_overlap_npi', label: 'groups_w_overlap_npi @ 96:4' },
  { id: 'recent_provider_extract', label: 'recent_provider_extract' },
  { id: 'assignment_history', label: 'assignment_history' },
  { id: 'AVRA_risk_adjuster__provider_measure', label: 'AVRA_risk_adjuster__provider_measure' },
  { id: 'match_history', label: 'match_history' },
  { id: 'AVRA_attribution', label: 'AVRA_attribution' },
  { id: 'demographic_capacity_cost', label: 'demographic_capacity_cost' },
  { id: 'pcpm_boe_crosswalk', label: 'pcpm_boe_crosswalk' },
  { id: 'nearest_member_provider_address', label: 'nearest_member_provider_address' },
  { id: 'match_value_table', label: 'match_value_table' },
  { id: 'filtered_valid_matches', label: 'filtered_valid_matches' },
  { id: 'last_successful_run', label: 'last_successful_run' },
  { id: 'experiment_exclusions', label: 'experiment_exclusions' },
  { id: 'compliance_adj_match_values', label: 'compliance_adj_match_values' },
  { id: 'pdb_provider_address', label: 'pdb_provider_address' },
  { id: 'provider_address', label: 'provider_address' },
  { id: 'power_sim_output_full', label: 'power_sim_output_full', comboId: 'accepted_matches' },
  { id: 'match_results', label: 'match_results' },
  { id: 'match_history_providers', label: 'match_history_providers' },
  { id: 'match_requests', label: 'match_requests' },
  { id: 'experiment_assignments', label: 'experiment_assignments' },
  { id: 'sink @ 1:0', label: 'sink @ 1:0' },
  { id: 'sink @ 6:1', label: 'sink @ 6:1' },
  { id: 'sink @ 9:0', label: 'sink @ 9:0' },
  { id: 'sink @ 12:2', label: 'sink @ 12:2', comboId: 'accepted_matches' },
  { id: 'sink @ 14:2', label: 'sink @ 14:2' },
  { id: 'sink @ 15:3', label: 'sink @ 15:3' },
  { id: 'sink @ 16:0', label: 'sink @ 16:0' },
  { id: 'sink @ 17:0', label: 'sink @ 17:0' },
  { id: 'sink @ 19:2', label: 'sink @ 19:2' },
  { id: 'sink @ 20:0', label: 'sink @ 20:0' },
  { id: 'sink @ 21:0', label: 'sink @ 21:0' },
  { id: 'sink @ 23:1', label: 'sink @ 23:1' },
  { id: 'sink @ 24:1', label: 'sink @ 24:1' },
  { id: 'sink @ 25:0', label: 'sink @ 25:0' },
  { id: 'sink @ 26:1', label: 'sink @ 26:1' },
  { id: 'sink @ 27:0', label: 'sink @ 27:0' },
  { id: 'sink @ 30:0', label: 'sink @ 30:0' },
  { id: 'sink @ 33:0', label: 'sink @ 33:0' },
  { id: 'sink @ 36:0', label: 'sink @ 36:0' },
  { id: 'sink @ 37:0', label: 'sink @ 37:0' },
  { id: 'sink @ 39:0', label: 'sink @ 39:0' },
  { id: 'sink @ 40:1', label: 'sink @ 40:1' },
  { id: 'sink @ 43:0', label: 'sink @ 43:0' },
  { id: 'sink @ 45:1', label: 'sink @ 45:1' },
  { id: 'sink @ 46:1', label: 'sink @ 46:1' },
  { id: 'sink @ 47:1', label: 'sink @ 47:1' },
  { id: 'sink @ 48:1', label: 'sink @ 48:1' },
  { id: 'sink @ 50:1', label: 'sink @ 50:1' },
  { id: 'sink @ 51:0', label: 'sink @ 51:0', comboId: 'accepted_matches' },
  { id: 'sink @ 54:2', label: 'sink @ 54:2' },
  { id: 'sink @ 55:0', label: 'sink @ 55:0', comboId: 'accepted_matches' },
  { id: 'sink @ 56:0', label: 'sink @ 56:0' },
  { id: 'sink @ 57:0', label: 'sink @ 57:0', comboId: 'accepted_matches' },
  { id: 'sink @ 58:0', label: 'sink @ 58:0', comboId: 'accepted_matches' },
  { id: 'sink @ 59:1', label: 'sink @ 59:1', comboId: 'accepted_matches' },
  { id: 'sink @ 60:1', label: 'sink @ 60:1',comboId: 'accepted_matches' },
  { id: 'sink @ 62:1', label: 'sink @ 62:1', comboId: 'accepted_matches' },
  { id: 'sink @ 64:1', label: 'sink @ 64:1', comboId: 'accepted_matches' },
  { id: 'sink @ 68:1', label: 'sink @ 68:1', comboId: 'accepted_matches' },
  { id: 'sink @ 69:0', label: 'sink @ 69:0', comboId: 'accepted_matches' },
  { id: 'sink @ 71:1', label: 'sink @ 71:1', comboId: 'accepted_matches' },
  { id: 'sink @ 73:1', label: 'sink @ 73:1', comboId: 'accepted_matches' },
  { id: 'sink @ 77:0', label: 'sink @ 77:0' },
  { id: 'sink @ 78:2', label: 'sink @ 78:2', comboId: 'accepted_matches' },
  { id: 'sink @ 79:0', label: 'sink @ 79:0' },
  { id: 'sink @ 80:0', label: 'sink @ 80:0', comboId: 'accepted_matches' },
  { id: 'sink @ 81:0', label: 'sink @ 81:0' },
  { id: 'sink @ 82:0', label: 'sink @ 82:0', comboId: 'accepted_matches' },
  { id: 'sink @ 83:0', label: 'sink @ 83:0' },
  { id: 'sink @ 85:0', label: 'sink @ 85:0', comboId: 'accepted_matches' },
  { id: 'sink @ 87:0', label: 'sink @ 87:0' },
  { id: 'sink @ 88:2', label: 'sink @ 88:2' },
  { id: 'sink @ 90:2', label: 'sink @ 90:2' },
  { id: 'sink @ 91:1', label: 'sink @ 91:1' },
  { id: 'sink @ 94:0', label: 'sink @ 94:0' },
  { id: 'sink @ 95:0', label: 'sink @ 95:0' },
  { id: 'sink @ 96:5', label: 'sink @ 96:5' },
  { id: 'sink @ 97:0', label: 'sink @ 97:0' },
]
